FROM nginx:latest

LABEL maintainer="AL-waleed Shihadeh <wshihadeh@gmail.com>"

COPY ./server/*.conf /etc/nginx/conf.d/server/
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/nginx.conf

